In [ ]:
''' 
You will be building  - Linear Regression. But before you build a model, 
you will need to have a method to extract the data and process it in your data frames and convert to numpy.  Y0ou have already
Complete the functions, readdata (similar to assignment 2), train, classify and LinRegaccuracy.
I have called the functions in the main program.

NASA data set, obtained from a series of aerodynamic and acoustic tests of two and three-dimensional airfoil blade 
sections conducted in an anechoic wind tunnel. The data set comprises different size NACA 0012 airfoils at various wind 
tunnel speeds and angles of attack. The span of the airfoil and the observer position were the same in all of the experiments. 
The data set has 6 attributes as given below. 
Now you will read a dataset for Machine Learning using pandas
filename = "airfoil_self_noise.dat.txt"
This is tab separated file with headers
Use appropriate command to read this data file and store the data into dataframe.
After that convert it to numpy
Then use numpy to split the data into training and test set.
The training data should have 80% of data, and the test data should ahve 20% data.
DO NOT USE SKLEARN LIBRARY
Details of Data set:
Attribute Information:

This problem has the following inputs:
(Attributes 1 to 5 form X_data) 
1. Frequency, in Hertzs. 
2. Angle of attack, in degrees. 
3. Chord length, in meters. 
4. Free-stream velocity, in meters per second. 
5. Suction side displacement thickness, in meters. 

The only output is (and Y_data): 
6. Scaled sound pressure level, in decibels. 
'''

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score

In [2]:
def readdata(filename, cols, delim = "\t"):    
    df = pd.read_csv(filename, delimiter=delim, names = cols)
    print(df.head())
    df.columns = cols
    features = cols[:len(cols)-1] #df.columns [:len(df.columns) - 1]

    y_label = [cols[len(cols)-1]]
    x_df = df[features]
    y_df = df[y_label]
    #x_df = (x_df - x_df.mean()) / x_df.std() #Dangerous as if any is 0 then you get nan

    x_data_set = np.array(pd.DataFrame(x_df, columns=features))
    y_data_set = np.array(pd.DataFrame(y_df, columns=y_label))
    x_mean = np.mean(x_data_set, axis=0)
    x_std = np.std(x_data_set, axis=0)
    for i in range (x_data_set.shape[1]):
        x_data_set [:,i] -= x_mean[i]
        if (x_std[i] != 0):
            x_data_set [:,i]/= x_std[i]

    x_data_train, x_data_test, y_data_train, y_data_test = train_test_split(
        x_data_set, y_data_set, test_size=0.35, shuffle=False)
    
    return x_data_train, y_data_train, x_data_test, y_data_test


In [3]:
cols = ['Frequency', 'AngleOfAttack', 'ChordLength', 'FreeStreamVelocity', 'SuctionSideDisplacementThickness', 'ScaledSoundPressureLevel']
x_data_train, y_data_train, x_data_test, y_data_test = readdata('airfoil_self_noise.dat.txt', cols)
print (x_data_train[0:5])
print (type(x_data_train), x_data_train.shape, x_data_test.shape, y_data_train.shape,y_data_test.shape)

   Frequency  AngleOfAttack  ChordLength  FreeStreamVelocity  \
0        800            0.0       0.3048                71.3   
1       1000            0.0       0.3048                71.3   
2       1250            0.0       0.3048                71.3   
3       1600            0.0       0.3048                71.3   
4       2000            0.0       0.3048                71.3   

   SuctionSideDisplacementThickness  ScaledSoundPressureLevel  
0                          0.002663                   126.201  
1                          0.002663                   125.201  
2                          0.002663                   125.951  
3                          0.002663                   127.591  
4                          0.002663                   127.461  
[[-0.6620227  -1.14640293  1.79929926  1.31293526 -0.64480461]
 [-0.59856135 -1.14640293  1.79929926  1.31293526 -0.64480461]
 [-0.51923465 -1.14640293  1.79929926  1.31293526 -0.64480461]
 [-0.40817728 -1.14640293  1.79929926  1.3

In [4]:
x_data_train.shape

(976, 5)

In [94]:
def train( x_data_train, y_data_train, l_rate, iterations):
    #Initialize W, b to 0 using np.zeros(), W.shape = (5,1), b.shape = (1,)
    W,b = np.zeros((x_data_train.shape[1],1)), np.zeros((1,))
    prevcost = 0
    numcost = 0
    #Iterate over "iterations" times in a for loop
    for i in range(iterations):
        hypo = np.dot(x_data_train,W)+b
        delta = hypo - y_data_train
        cost = np.sum(np.power(delta,2))/2*len(x_data_train)
        deltacost = cost - prevcost
        #print(i,cost)
        dw = np.dot(x_data_train.T,delta)/len(x_data_train)
        W = W-l_rate*dw
        b = b - np.sum((l_rate*delta))/len(x_data_train)
        prevcost = cost
        if np.abs(deltacost) < 0.0003:
            numcount +=1
        else: 
            numcount=0
    return W, b

In [103]:
def classify(x_data_test, W, b):
    return np.dot(x_data_test,W)+b

In [101]:
def LinRegaccuracy(y_data_test, y_pred_test):

    total_error = 0
    for i in range(0, len(y_data_test)):
        errSet= abs((y_pred_test[i] - y_data_test[i]) / y_data_test[i])
        total_error += errSet
    total_error = (total_error / len(y_data_test))
    accuracyScore = 1 - total_error
    return accuracyScore

In [104]:
cols = ['Frequency', 'AngleOfAttack', 'ChordLength', 'FreeStreamVelocity', 'SuctionSideDisplacementThickness', 'ScaledSoundPressureLevel']
x_data_train, y_data_train, x_data_test, y_data_test = readdata('airfoil_self_noise.dat.txt', cols)

W, b = train(x_data_train, y_data_train, 0.001, 60000)
y_prediction_train = classify(x_data_train, W, b)
y_prediction_test = classify(x_data_test, W, b)

accuracy_test = LinRegaccuracy(y_data_test, y_prediction_test)
accuracy_train = LinRegaccuracy(y_data_train, y_prediction_train)

print("accuracy train: ", accuracy_train, "accuracy test: ", LinRegaccuracy)
# print ("Sklearn Accuracy score=Training", accuracy_score(list(y_prediction_train),list( y_data_train)))
# print ("Sklearn Accuracy score=Testing", accuracy_score(y_prediction_test, y_data_test))
print("MSE test: ", mean_squared_error(y_data_test, y_prediction_test))
print("MSE train: ", mean_squared_error(y_data_train, y_prediction_train))


   Frequency  AngleOfAttack  ChordLength  FreeStreamVelocity  \
0        800            0.0       0.3048                71.3   
1       1000            0.0       0.3048                71.3   
2       1250            0.0       0.3048                71.3   
3       1600            0.0       0.3048                71.3   
4       2000            0.0       0.3048                71.3   

   SuctionSideDisplacementThickness  ScaledSoundPressureLevel  
0                          0.002663                   126.201  
1                          0.002663                   125.201  
2                          0.002663                   125.951  
3                          0.002663                   127.591  
4                          0.002663                   127.461  
accuracy train:  [0.97469264] accuracy test:  <function LinRegaccuracy at 0x000001A15E582798>
MSE test:  38.316887949120236
MSE train:  16.12674473754933
